export const IMAGE_SIZES = [
    {
        label: 'Small (256 X 256)',
        value: 'Small',
    },
    {
        label: 'Medium (512 X 512)',
        value: 'Medium',
    },
    {
        label: 'Large (1024 X 1024)',
        value: 'Large',
    },
]

export const promptList = [
    'Mechanical Dawn, Technology City, a Mechanical Transformer, epic fantasy art',
    'Centered portrait of an ultra detailed Mechanical Cyberpunk Female Android, looking into the camera, intricate, elegant, super highly detailed, smooth, sharp focus, no blur, no dof, extreme illustration, Unreal',
    'wolf portrait, ferns, butterflies, oilpainting, cinematic lighting',
    'A pretty woman, delicate features directed gaze, Earrings,concept art, digital painting, illustration, 8k, studio lighting',
    'Mechanical Dawn, Technology City, a Mechanical Transformer, epic fantasy art',
    'Iridescent armor, long wild white hair!! covered chest!!! fantasy, d & d, intricate ornate details, digital painting, pretty face, symmetry',
    'A 28 mm closeup photo of a tesla cybertruck a on wet floor of a photo studio, intricate, hyper detailed, smooth, high contrast, volumetric lighting, octane, moebius, greg rutkowski, blade runner, ripley scott, synthwave, cinematic',
    'Silicon valley virtual reality 10 th anniversary, beautiful! woman with glasses, cyberpunk art by android jones, cyberpunk art by beeple, synthwave, darksynth, quantum tracerwave, wireframes',
    'Centered portrait of an ultra detailed Mechanical Cyberpunk Female Android, looking into the camera, intricate, elegant, super highly detailed, smooth, sharp focus, no blur, no dof, extreme illustration, Unreal',
    'Beautiful organic house made of imaginary plants in a forest, architectural render, futuresynth, chillwave',
    'Hand drawn cute gnomes face in autumn disguise holding pumpkin and maple leaf, detailed face, low angle, high detail, warm lighting, volumetric, godrays, vivid, beautiful',
    'Very atmospheric Technology City, a tiny Motorcycle, fantasy art',
    'An astronaut resting on mars in a beach chair, vibrant lighting, elegant, highly detailed, smooth, sharp focus, illustration, beautiful, geometric',
    'Full body 3d render of brown man with beard wearing tobacco brown pullover, glasses, white collar',
    'A pretty woman, delicate features directed gaze, Earrings',
    'An astronaut resting on mars in a beach chair, vibrant lighting, elegant, highly detailed, smooth, sharp focus, illustration, beautiful, geometric',
    'A 28 mm closeup photo of a tesla cybertruck a on wet floor of a photo studio, intricate, hyper detailed, smooth, high contrast, volumetric lighting, octane, moebius, greg rutkowski, blade runner, ripley scott, synthwave, cinematic',
    'Robert Pattison portrait, dystopia core, hyperrealistic, apocalyptic, highly detailed exoskeleton armor, dramatic, sharp focus, hero, gape, epic, perfectly symmetrical face, perfect eyes, intricate',
    'anime key visual of elegant young female, long blonde hair and large eyes, finely detailed perfect face, laying down in the grass at sunset, golden hour sunset lighting, background blur bokeh',
    'Iridescent armor, long wild white hair!! covered chest!!! fantasy, d & d, intricate ornate details, digital painting, pretty face, symmetry',
    'wolf portrait, ferns, butterflies, oilpainting, cinematic lighting',
    '4K HD, high detail photograph, shot with Sigma f/4.2, 250 mm sharp lens, shallow depth of field, White golden retriever, consistent, high detailed light refraction, high level texture render',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
]